# Generated by Django 3.1.14 on 2022-06-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20220606_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_to',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='previous_evolutions', to='pokemon_entities.pokemon'),
        ),
    ]
